// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-_bRafyeAWvyVNtUqEfjiXB_ZLMZdsU',
    appId: '1:337367330086:web:c23415b2e25813965025e7',
    messagingSenderId: '337367330086',
    projectId: 'chat-app-efc31',
    authDomain: 'chat-app-efc31.firebaseapp.com',
    storageBucket: 'chat-app-efc31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACSEieRitSxltvHs98XWXch3nvMuxR4UQ',
    appId: '1:337367330086:android:70117d550ccf66a45025e7',
    messagingSenderId: '337367330086',
    projectId: 'chat-app-efc31',
    storageBucket: 'chat-app-efc31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIenGYAxPkd8kMivMzV804BnUs9ULdVcE',
    appId: '1:337367330086:ios:b67b298e3f0fd8075025e7',
    messagingSenderId: '337367330086',
    projectId: 'chat-app-efc31',
    storageBucket: 'chat-app-efc31.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIenGYAxPkd8kMivMzV804BnUs9ULdVcE',
    appId: '1:337367330086:ios:b67b298e3f0fd8075025e7',
    messagingSenderId: '337367330086',
    projectId: 'chat-app-efc31',
    storageBucket: 'chat-app-efc31.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
